# server port config
server:
  port: 8080

# oracle driver config
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@oracle.coffit.site:1521:xe
    username: C##GOLANG
    password: GOLANG
    hikari:
      auto-commit: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  freemarker:
    cache: false
  web:
    resources:
      static-locations: classpath:/images/

  jpa:
    generate-ddl: true
    show-sql: true
    database: oracle
    properties:
      hibernate:
        '[format_sql]': true
        hbm2ddl:
          auto: update

# 이미지 저장할 위치와 응답할 때 이미지 주소 세팅
image:
  # WebConfig에 세팅
  add-resource-locations: classpath:/static/images/
  add-resource-handler: /images/**
  # ProductService에 세팅
  image-dir: src/main/resources/static/images
  image-url: http://localhost:8080/images/



# mybatis config
mybatis:
  mapper-locations: mybatis/*.xml