# server port config
server:
  port: 8080

# oracle driver config
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@oracle.coffit.site:1521:xe
    username: C##GOLANG
    password: GOLANG
    hikari:
      auto-commit: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true #개발 : true 운영 : false
  freemarker:
    cache: true #개발 : false 운영 : true

  jpa:
    generate-ddl: true #개발 : true 운영: false 스키마 자동생성 기능
    show-sql: true  #개발 : true 운영: false SQL쿼리 출력
    database: oracle
    properties:
      hibernate:
        '[format_sql]': true #개발 : true 운영: false sql 분석 쉽게
        hbm2ddl:
          auto: update #개발 : update 운영: none

aws:
  accessKey: AKIA6PF2SY7JQO4IFD4G
  secretAccessKey: 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

oauth:
  Kakao:
    client-id: 202bf1013addf514255b52a8c9c69ebf
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  naver:
    secret: iHe8ItSSso
    client-id: T0mWG2VjAfBH9cYz6Qrf
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com

# mybatis config
mybatis:
  mapper-locations: mybatis/*.xml

# aws 설정
# 사용할 S3 bucket region 입력
cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
