# server port config
server:
  port: 8080

# oracle driver config
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@oracle.coffit.site:1521:xe
    username: C##GOLANG
    password: GOLANG
    hikari:
      auto-commit: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false #개발 : true 운영 : false
  freemarker:
    cache: true #개발 : false 운영 : true
  web:
    resources:
      static-locations: classpath:/imgs/

  jpa:
    generate-ddl: false #개발 : true 운영: false 스키마 자동생성 기능
    show-sql: false  #개발 : true 운영: false SQL쿼리 출력
    database: oracle
    properties:
      hibernate:
        '[format_sql]': false #개발 : true 운영: false sql 분석 쉽게
        hbm2ddl:
          auto: none #개발 : update 운영: none

# 이미지 저장할 위치와 응답할 때 이미지 주소 세팅
image:
  # WebConfig에 세팅
  add-resource-locations: classpath:/static/imgs/
  add-resource-handler: /imgs/**
  # ProductService에 세팅
  image-dir: src/main/resources/static/imgs
  image-url: http://localhost:8080/imgs/

#oauth:
#  kakao:
#    client-id: 202bf1013addf514255b52a8c9c69ebf
#    url:
#      auth: https://kauth.kakao.com
#      api: https://kapi.kakao.com
#  naver:
#    secret: W_2DmcLfYU
#    client-id: Y2i4SlApP7A1KZsUoott
#    url:
#      auth: https://nid.naver.com
#      api: https://openapi.naver.com


# mybatis config
mybatis:
  mapper-locations: mybatis/*.xml


