# server port config
server:
  port: 8080

# oracle driver config
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@oracle.coffit.site:1521:xe
    username: C##GOLANG
    password: GOLANG
    hikari:
      auto-commit: false

  jpa:
    generate-ddl: true
    show-sql: true
    database: oracle
    properties:
      hibernate:
        '[format_sql]': true
        hbm2ddl:
          auto: update

jwt:
  secret-key: ipqjRiEoJ7_EdLCaX_6kAwI95NrX3_5uiDgnzuwjCj11mgAAAYhNDF3k

#oauth:
#  kakao:
#    client-id: 202bf1013addf514255b52a8c9c69ebf
#    url:
#      auth: https://kauth.kakao.com
#      api: https://kapi.kakao.com
#  naver:
#    secret: W_2DmcLfYU
#    client-id: Y2i4SlApP7A1KZsUoott
#    url:
#      auth: https://nid.naver.com
#      api: https://openapi.naver.com


# mybatis config
mybatis:
  mapper-locations: mybatis/mappers/*.xml
